base_url = "https://hypnosister-code.github.io/hhhhjjjoorn-blogs"
title = "MÓJ BLOG"

# description removed by user request
default_language = "pl"
author = "Twój Nick"
compile_sass = false
build_search_index = false

[extra]
# Dodatkowe zmienne
